### ISSUE TITLE
May I know why a "clear" needed here

### ISSUE THREAD

**Issue by jackson-jiang** [tmattsson/gs1utils#3]
https://github.com/tmattsson/gs1utils/blob/00265aecddc19625b732f37e0a858cd42c108219/src/main/java/se/injoin/gs1utils/ElementStrings.java#L318

Hi tamattsson,
we are using your package to parse gs1 code. And we came across some problem when using it.  would you help?
we parse 220118 as a date and the result is 1922-01-18 which 2022-01-18 was expected.
We check your code and there is a statement "Calendar.clear()" set the current year to 1970. According to the gs1 specification, we need to use "current year" to calculate dates. but Calendar.clear() will set current year to 1970.

**Comment by tmattsson** [comment]
This is indeed a bug. The calendar should be cleared just not that early.

**Comment by tmattsson** [comment]
Fix has been pushed.
